---
title: "Data exploration"
author: "Katarzyna Sidorczuk"
date: "1/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 12, fig.height = 10)
library(dplyr)
library(biogram)
library(seqR)
library(ggbiplot)
library(Rtsne)
library(ggplot2)
library(plotly)

source("./functions/do_cdhit.R")
source("./functions/get_composition_matrix.R")
source("./functions/reduce_dimensionality.R")

data_path <- "/home/kasia/UniProt_Plastid_Proteins/UniProt_data/"
```

## New groups of sequences and CD-HIT reduction

```{r echo = FALSE}
groups <- c("N_OM", "N_IM", "P_IM", "N_S", "P_S", "N_S_peripheral-TM", "P_S_peripheral-TM",
            "N_S_peripheral-IM", "P_S_peripheral-IM", "N_TM", "P_TM", "N_TL_peripheral", 
            "P_TL_peripheral", "N_TL", "P_TL")

df <- lapply(groups, function(ith_group) {
  seqs <- read_fasta(paste0(data_path, ith_group, ".fasta"))
  filtered_1 <- filter_with_cdhit(seqs, 1)
  filtered_0.95 <- filter_with_cdhit(seqs, 0.95)
  filtered_0.9 <- filter_with_cdhit(seqs, 0.9)
  data.frame(Dataset = ith_group,
             all = length(seqs),
             cdhit_1 = length(filtered_1),
             cdhit_0.95 = length(filtered_0.95),
             cdhit_0.9 = length(filtered_0.9))
}) %>% bind_rows()

knitr::kable(df)

```

## PCA - all protein groups
```{r}
ngram_comp <- get_composition_matrix("./sequences_after_cdhit/", groups, 90)

pca_all <- do_pca(ngram_comp)
save(pca_all, file = "./results/PCA_all.rda")

all_labels <- ngram_comp[["Dataset"]]
plot_pca_res(pca_all, labels = all_labels)
```

## PCA - all proteins, larger groups

```{r}
labels_large_groups <- case_when(all_labels == "N_OM" ~ "N_OM",
                                 all_labels == "N_IM" ~ "N_IM", 
                                 all_labels == "P_IM" ~ "P_IM", 
                                 all_labels %in% c("N_S", "N_S_peripheral-TM", "N_S_peripheral-IM") ~ "N_S", 
                                 all_labels %in% c("P_S", "P_S_peripheral-TM", "P_S_peripheral-IM") ~ "P_S", 
                                 all_labels == "N_TM" ~ "N_TM",
                                 all_labels == "P_TM" ~ "P_TM",
                                 all_labels %in% c("N_TL_peripheral", "N_TL") ~ "N_TL",
                                 all_labels %in% c("P_TL_peripheral", "P_TL") ~ "P_TL")
plot_pca_res(pca_all, labels = labels_large_groups) +
  scale_fill_manual("Dataset", labels = c("N_OM", "N_IM", "P_IM", "N_S", "P_S", "N_TM", "P_TM", "N_TL", "P_TL"),
                       values = c("#8210c9", "#344feb", "#69cdff", "#ccbf10", "#fff575", "#911a1a", "#ff7d7d", "#118a0c", "#9fff9c"))
```

## PCA - nuclear-encoded proteins

```{r}
ngram_comp_nucl <- filter(ngram_comp, Dataset %in% c("N_OM", "N_IM", "N_S", "N_S_peripheral-TM", "N_S_peripheral-IM", 
                                                     "N_TM", "N_TL_peripheral", "N_TL"))
pca_nucl <- do_pca(ngram_comp_nucl)
save(pca_nucl, file = "./results/PCA_nucl.rda")
nucl_labels <- ngram_comp_nucl[["Dataset"]]
plot_pca_res(pca_nucl, labels = nucl_labels)
```

## PCA - plastid-encoded proteins

```{r}
ngram_comp_pl <- filter(ngram_comp, Dataset %in% c("P_IM", "P_S", "P_S_peripheral-TM", "P_S_peripheral-IM", 
                                                   "P_TM", "P_TL_peripheral", "P_TL"))
pca_pl <- do_pca(ngram_comp_pl)
save(pca_pl, file = "./results/PCA_pl.rda")
pl_labels <- ngram_comp_pl[["Dataset"]]
plot_pca_res(pca_pl, labels = pl_labels)
```

## tSNE - all proteins 2D

```{r}
tsne_all_2d <- do_tsne(ngram_comp, dims = 2)
save(tsne_all_2d, file = "./results/tsne_all_2d.rda")
plot_2d_tsne(tsne_all_2d, labels = labels_large_groups) +
  scale_color_manual("Dataset", labels = c("N_OM", "N_IM", "P_IM", "N_S", "P_S", "N_TM", "P_TM", "N_TL", "P_TL"),
                     values = c("#8210c9", "#344feb", "#69cdff", "#ccbf10", "#fff575", "#911a1a", "#ff7d7d", "#118a0c", "#9fff9c"))
```

## tSNE - all proteins 3D 
```{r}
tsne_all_3d <- do_tsne(ngram_comp, dims = 3)
save(tsne_all_3d, file = "./results/tsne_all_3d.rda")
plot_3d_tsne(tsne_all_3d, labels = labels_large_groups, 
             colors = c("#8210c9", "#344feb", "#69cdff", "#ccbf10", "#fff575", "#911a1a", "#ff7d7d", "#118a0c", "#9fff9c"))
```

## tSNE - nuclear-encoded proteins 2D

```{r}
tsne_nucl_2d <- do_tsne(ngram_comp_nucl, dims = 2)
save(tsne_nucl_2d, file = "./results/tsne_nucl_2d.rda")
plot_2d_tsne(tsne_nucl_2d, labels = ngram_comp_nucl[["Dataset"]])
```

## tSNE - nuclear-encoded proteins 3D 
```{r}
tsne_nucl_3d <- do_tsne(ngram_comp_nucl, dims = 3)
save(tsne_nucl_3d, file = "./results/tsne_nucl_3d.rda")
plot_3d_tsne(tsne_nucl_3d, labels = ngram_comp_nucl[["Dataset"]],
             colors = c("#8210c9", "#344feb", "#69cdff", "#fff575", "#911a1a", "#ff7d7d", "#118a0c", "#9fff9c"))
```

## tSNE - plastid-encoded proteins 2D

```{r}
tsne_pl_2d <- do_tsne(ngram_comp_pl, dims = 2)
save(tsne_pl_2d, file = "./results/tsne_pl_2d.rda")
plot_2d_tsne(tsne_pl_2d, labels = ngram_comp_pl[["Dataset"]])
```

## tSNE - plastid-encoded proteins 3D 
```{r}
tsne_pl_3d <- do_tsne(ngram_comp_pl, dims = 3)
save(tsne_pl_3d, file = "./results/tsne_pl_3d.rda")
plot_3d_tsne(tsne_pl_3d, labels = ngram_comp_pl[["Dataset"]],
             colors = c("#8210c9", "#344feb", "#69cdff", "#911a1a", "#ff7d7d", "#118a0c", "#9fff9c"))
```

