---
title: "Nuclear-encoded proteins"
author: "Katarzyna Sidorczuk"
date: "29/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 12, fig.height = 8)

library(biogram)
library(seqR)
library(targets)
library(tidyr)
library(ggplot2)
library(ggbiplot)
library(dplyr)


props <- data.frame(prop = c("BIGC670101", "ARGP820101", "CHAM820101", "CHOP780201", "CHOP780202", 
                             "CHOP780203", "FASG760101", "FASG760104", "FASG760105", "FAUJ880103", 
                             "KLEP840101", "KYTJ820101", "ZIMJ680103", "ENGD860101", "FASG890101"),
                    description = c("Residue volume (Bigelow, 1967)", "Hydrophobicity index (Argos et al., 1982)",
                                    "Polarizability parameter (Charton-Charton, 1982)", "Normalized frequency of alpha-helix (Chou-Fasman, 1978b)",
                                    "Normalized frequency of beta-sheet (Chou-Fasman, 1978b)", "Normalized frequency of beta-turn (Chou-Fasman, 1978b)",
                                    "Molecular weight (Fasman, 1976)", "pK-N (Fasman, 1976)", "pK-C (Fasman, 1976)", 
                                    "Normalized van der Waals volume (Fauchere et al., 1988)", "Net charge (Klein et al., 1984)",
                                    "Hydropathy index (Kyte-Doolittle, 1982)", "Polarity (Zimmerman et al., 1968)",
                                    "Hydrophobicity index (Engelman et al., 1986)", "Hydrophobicity index (Fasman, 1989)"))


encode_seq <- function(x, property) {
  sapply(x, function(ith_seq) {
    mean(aaprop[property, tolower(ith_seq)])
  })
}

calculate_properties <- function(datasets) {
  lapply(names(datasets), function(ith_dataset) {
    ds_neg <- datasets[[ith_dataset]]
    data.frame(prot = names(ds_neg),
               dataset = ith_dataset,
               len = lengths(ds_neg),
               BIGC670101 = encode_seq(ds_neg, "BIGC670101"),
               ARGP820101 = encode_seq(ds_neg, "ARGP820101"),
               CHAM820101 = encode_seq(ds_neg, "CHAM820101"),
               CHOP780201 = encode_seq(ds_neg, "CHOP780201"),
               CHOP780202 = encode_seq(ds_neg, "CHOP780202"),
               CHOP780203 = encode_seq(ds_neg, "CHOP780203"),
               FASG760101 = encode_seq(ds_neg, "FASG760101"),
               FASG760104 = encode_seq(ds_neg, "FASG760104"),
               FASG760105 = encode_seq(ds_neg, "FASG760105"),
               FAUJ880103 = encode_seq(ds_neg, "FAUJ880103"),
               KLEP840101 = encode_seq(ds_neg, "KLEP840101"),
               KYTJ820101 = encode_seq(ds_neg, "KYTJ820101"),
               ZIMJ680103 = encode_seq(ds_neg, "ZIMJ680103"),
               ENGD860101 = encode_seq(ds_neg, "ENGD860101"),
               FASG890101 = encode_seq(ds_neg, "FASG890101"))
  }) %>% bind_rows()
}

withr::with_dir("../",
                tar_load(c(traintest_data_df, benchmark_data_df, traintest, benchmark)))
colors <- c("OM" = "#8210c9", "N_IM" = "#344feb", "N_TM" = "#911a1a", "N_S" = "#118a0c")
colors_all <- c("OM" = "#8210c9", "N_IM" = "#344feb", "N_TM" = "#911a1a", "N_S" = "#118a0c", "P_IM" = "#69cdff")

OM_t <- traintest[which(names(traintest) %in% filter(traintest_data_df, dataset == "N_OM")[["seq_name"]])]
N_IM_t <- traintest[which(names(traintest) %in% filter(traintest_data_df, dataset == "N_IM")[["seq_name"]])]
N_TM_t <- traintest[which(names(traintest) %in% filter(traintest_data_df, dataset == "N_TM")[["seq_name"]])]
N_S_t <- traintest[which(names(traintest) %in% filter(traintest_data_df, dataset == "N_S")[["seq_name"]])]
P_IM_t <- traintest[which(names(traintest) %in% filter(traintest_data_df, dataset == "P_IM")[["seq_name"]])]

ds <- list("OM" = OM_t, "N_IM" = N_IM_t, "N_TM" = N_TM_t, "N_S" = N_S_t)
ds_all <- list("OM" = OM_t, "N_IM" = N_IM_t, "N_TM" = N_TM_t, "N_S" = N_S_t, "P_IM" = P_IM_t)

aac <- lapply(names(ds), function(ith_set) {
  aa <- as.matrix(table(unlist(unname(ds[[ith_set]]))))/length(unlist(ds[[ith_set]])) 
    data.frame(aa = row.names(aa),
               freq = aa[,1],
               dataset = ith_set)
}) %>% bind_rows()
prop_df <- calculate_properties(ds)

aac_all <- lapply(names(ds_all), function(ith_set) {
  aa <- as.matrix(table(unlist(unname(ds_all[[ith_set]]))))/length(unlist(ds_all[[ith_set]])) 
    data.frame(aa = row.names(aa),
               freq = aa[,1],
               dataset = ith_set)
}) %>% bind_rows()
prop_df_all <- calculate_properties(ds_all)
```


## Amino acid composition 

```{r}
ggplot(aac_all, aes(x = dataset, y = freq, fill = dataset, group = dataset, color = dataset)) +
  geom_col(position = "dodge", alpha = 0.5) +
  facet_wrap(~aa, scales = "free_x") +
  scale_fill_manual(values = colors_all) +
  scale_color_manual(values = colors_all) +
  theme_bw() +
  theme(legend.position = "none") 
```
<br>

Only for envelope and stroma
```{r}
aac %>% 
  filter(dataset %in% c("OM", "N_S", "N_IM")) %>% 
  ggplot(aes(x = dataset, y = freq, fill = dataset, group = dataset, color = dataset)) +
  geom_col(position = "dodge", alpha = 0.5) +
  facet_wrap(~aa, scales = "free_x") +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  theme_bw() +
  theme(legend.position = "none") 
```


## PCA on physicochemical properties distribution
```{r}
pca_prop_res <- prcomp(prop_df[, 4:(ncol(prop_df))], center = TRUE, scale = TRUE)

ggbiplot(pca_prop_res, choices = 1:2, groups = prop_df[["dataset"]]) +
  ggtitle("PCA on means of physicochemical properties") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_color_manual("Dataset", values = colors)
```


## Hydrophobicity and charge distribution
```{r}
prop_df %>% 
  ggplot(aes(x = ARGP820101, y = KLEP840101, color = factor(dataset), fill = factor(dataset))) +
  geom_jitter(aes(alpha = 0.05)) +
  stat_density_2d(aes(alpha = ..level..), geom = "polygon", color = "black", size = 0.1, adjust = 1/2) +
  theme_bw() +
  xlab("Hydrophobicity index (Argos et al., 1982)") +
  ylab("Net charge (Klein et al., 1984)") +
  facet_wrap(~dataset) +
  scale_fill_manual("Dataset", values = colors) +
  scale_color_manual("Dataset", values = colors) +
  theme(legend.position = "none")
```


## Physicochemical properties distributions
```{r fig.width = 4, fig.height = 3, message = FALSE}
lapply(colnames(prop_df)[4:ncol(prop_df)], function(ith_prop) {
  plot_dat <- prop_df[, c("prot", "dataset", ith_prop)] %>% 
    setNames(c("prot", "Dataset", "Property"))
  ggplot(plot_dat, aes(x = Dataset, y = Property, group = Dataset, fill = Dataset)) +
    geom_violin(alpha = 0.5) +
    ggtitle(props[["description"]][which(props[["prop"]] == ith_prop)]) + 
    xlab(NULL) +
    ylab(NULL) +
    theme_bw(base_size = 8) +
    theme(plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
    scale_fill_manual("Dataset", values = colors)
})
```
